apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestProxy
metadata:
  name: kafkarestproxy
spec:
  image:
    application: confluentinc/cp-kafka-rest:7.3.0
    init: confluentinc/confluent-init-container:2.5.0

